<h1>Liste de nos Jeux Vidéos!</h1>
<h2>Liste de nos Jeux Vidéos!</h2>
<!-- Texte principal -->
<p class="texte_prems">
<p class="texte_prems">Pour rechercher les jeux vidéos que nous
	possèdons, choisissez le type de jeux que vous recherchez dans les listes
	déroulantes ci-contre:
<form id="listeGenreJV"
	action="<?php echo Atomik::url('Collection_JV'); ?>" method="post">
	<select name="ListeGenreJV">
		<option value="Vide"></option>
		<option value="Tout">Tout</option>
		<?php
		While($Donnees=$ReponseJV->fetch())
		{
			echo '<option value="'; echo $Donnees['Genre']; echo '">'; echo $Donnees['Genre']; echo '</option>';
		}
		$ReponseJV->closeCursor();
		?>
	</select> <select name="ListeConsole">
		<option value="Vide"></option>
		<?php
		While($Donnees=$ReponseConsole->fetch())
		{
			echo '<option value="'; echo $Donnees['Console']; echo '">'; echo $Donnees['Console']; echo '</option>';
		}
		$ReponseConsole->closeCursor();
		?>
	</select> <select name="ListeLecteur">
		<option value="Vide"></option>
		<?php
		While($Donnees=$ReponseJoueur->fetch())
		{
			echo '<option value="'; echo $Donnees['Joueur']; echo '">'; echo $Donnees['Joueur']; echo '</option>';
		}
		$ReponseJoueur->closeCursor();
		?>
	</select> <input type="submit" value="Envoyer" />
	<?php

	
	$page = '';

	// Affichage de la liste
	if(isset($Affichage) and count($Affichage) > 0) {
		echo $Tableau;

		// Affichage des numéro de page
		$page.='<p class="ListePage">';
		for ($i=1; $i < count($Affichage)/$maxLignes+1; $i++) {
			$page.='<a class="LienListePage" href="'.Atomik::url('Collection_JV', Array('page' => $i)).'">';
			
			if ($i>=count($Affichage)/$maxLignes)
			{
				$page.=$i;
			}
			else if ($i < count($Affichage))
			{
				$page.=$i.' - ';
			}
			$page.='</a>';
		}
		$page.='</p>';
	}
	else {
		$page.='<p>&nbsp;</p>';
	}
	echo $page;
	?>
</form>
</p>
