<h1>Liste de mes bandes dessinées!</h1>
<h2>Liste de mes bandes dessinées!</h2>
<!-- Texte principal -->
<p class="texte_prems">
<p class="texte_prems">Pour rechercher les bandes dessinées que nous
	possèdons, choisissez le type de BD que vous recherchez dans la liste
	déroulante ci-contre:
<form id="listeGenreBD"
	action="<?php echo Atomik::url('Collection_BD'); ?>" method="post">
	<select name="ListeGenreBD">
		<option value="Vide"></option>
		<option value="Tout">Tout</option>
		<?php
		While($Donnees=$ReponseBD->fetch())
		{
			echo '<option value="'; echo $Donnees['Genre']; echo '">'; echo $Donnees['Genre']; echo '</option>';
		}
		$ReponseBD->closeCursor();
		?>
	</select> <select name="ListeLecteur">
		<option value="Vide"></option>
		<?php
		While($Donnees=$ReponseLecteur->fetch())
		{
			echo '<option value="'; echo $Donnees['Lecteur']; echo '">'; echo $Donnees['Lecteur']; echo '</option>';
		}
		$ReponseLecteur->closeCursor();
		?>
	</select> <select name="ListeType">
		<option value="Vide"></option>
		<?php
		While($Donnees=$ReponseType->fetch())
		{
			echo '<option value="'; echo $Donnees['Type']; echo '">'; echo $Donnees['Type']; echo '</option>';
		}
		$ReponseType->closeCursor();
		?>
	</select> <input type="submit" value="Envoyer" />
	<?php

	//$pageCourante = 0;
	$maxLignes = 10;
	$page = '';

	// Affichage de la liste
	if(isset($Resultat)) {
		$Affichage=$Resultat->fetchAll();
		echo '<table class="AffichResult">';
		echo "<tr>";
		echo "<th>";
		echo 'Nom';
		echo "</th>";
		echo "<th>";
		echo 'Titre';
		echo "</th>";
		echo "<th>";
		echo 'Volume(s)';
		echo "</th>";
		echo "<th>";
		echo 'Auteur';
		echo "</th>";
		echo "<th>";
		echo 'Editeur';
		echo "</th>";
		echo "<th>";
		echo 'Genre';
		echo "</th>";
		echo "<th>";
		echo 'Type';
		echo "</th>";
		echo "<th>";
		echo 'Lecteur';
		echo "</th>";
		echo "</tr>";
		for ($i=($pageCourante-1)*$maxLignes; $i < $maxLignes*$pageCourante; $i++)
		{
			echo "<tr>";
			echo "<td>";
			echo $Affichage[$i]['Nom'];
			echo "</td>";
			echo "<td>";
			echo $Affichage[$i]['Titre'];
			echo "</td>";
			echo "<td>";
			echo $Affichage[$i]['Volumes achetés'];
			echo "</td>";
			echo "<td>";
			echo $Affichage[$i]['Auteur'];
			echo "</td>";
			echo "<td>";
			echo $Affichage[$i]['Editeur'];
			echo "</td>";
			echo "<td>";
			echo $Affichage[$i]['Genre'];
			echo "</td>";
			echo "<td>";
			echo $Affichage[$i]['Type'];
			echo "</td>";
			echo "<td>";
			echo $Affichage[$i]['Lecteur'];
			echo "</td>";
			echo "</tr>";
		}
		echo "</table>";
		
		echo "</br>";
		echo "</br>";

		// Affichage des numéro de page
		$page.='<p>';
		for ($i=1; $i < count($Affichage)/$maxLignes+1; $i++) {
			$page.='<a href="'.Atomik::url('Collection_BD', Array('page' => $i)).'">';
			$page.='('.$i.')-';
			$page.='</a>';
		}
		$page.='</p>';
	}
	else {
		$page.='<p>&nbsp;</p>';
	}
	echo $page;
	?>
</form>
</p>
</p>
