<h1>Liste de nos CD!</h1>
<h2>Liste de nos CD!</h2>
<!-- Texte principal -->
<p class="texte_prems">
<p class="texte_prems">Pour rechercher les CD que nous
	possèdons, choisissez le type de CD que vous recherchez dans les listes
	déroulantes ci-contre:
<form id="listeGenreBD"
	action="<?php echo Atomik::url('Collection_CD'); ?>" method="post">
	<select name="ListeArtiste">
		<option value="Vide"></option>
		<?php
		While($Donnees=$ReponseArtiste->fetch())
		{
			echo '<option value="'; echo $Donnees['Artiste']; echo '">'; echo $Donnees['Artiste']; echo '</option>';
		}
		$ReponseArtiste->closeCursor();
		?>
	</select> <select name="ListeLecteur">
		<option value="Vide"></option>
		<?php
		While($Donnees=$ReponseLecteur->fetch())
		{
			echo '<option value="'; echo $Donnees['Lecteur']; echo '">'; echo $Donnees['Lecteur']; echo '</option>';
		}
		$ReponseLecteur->closeCursor();
		?>
	</select> <input type="submit" value="Envoyer" />
	<?php

	
	$page = '';

	// Affichage de la liste
	if(isset($Affichage) and count($Affichage) > 0) {
		echo $Tableau;

		// Affichage des numéro de page
		$page.='<p class="ListePage">';
		for ($i=1; $i < count($Affichage)/$maxLignes+1; $i++) {
			$page.='<a class="LienListePage" href="'.Atomik::url('Collection_CD', Array('page' => $i)).'">';
			
			if ($i>=count($Affichage)/$maxLignes)
			{
				$page.=$i;
			}
			else if ($i < count($Affichage))
			{
				$page.=$i.' - ';
			}
			$page.='</a>';
		}
		$page.='</p>';
	}
	else {
		$page.='<p>&nbsp;</p>';
	}
	echo $page;
	?>
</form>
</p>
